### ISSUE TITLE
Styling, Functional Cards

### ISSUE THREAD

**Issue by devchristiansimon** [devchristiansimon/capstone-user-stories#2]
## Value Proposition

**As a user
**I need visible cards
**to be able to click on them so a new frame appears

## Description

![ExcalidrawGoal](https://user-images.githubusercontent.com/14675664/179203138-a149156c-b99a-4b5c-a53a-d2ddab124b63.png)

## Acceptance Criteria

- [ ] global style of the app (375x667px)
- [ ] cards as flexboxes
- [ ] interaction with cards to open a frame

## Tasks

(for developers team)

- [ ] global styling
- [ ] component/header
- [ ] component/footer (empty)
- [ ] cards styling
- [ ] component cards
- [ ] putting cards in array
- [ ] set object for each card-array
- [ ] clickable function to open a new iFrame
- [ ] implement individual object in iFrame
- [ ] close-button for iFrame

**Comment by chris-yooo** [comment]
i think the iframe that popup when you click on a card/video, and the iframe close function enough for your second user story :)

can you scroll your cards to left or right ? or you have only 3 cards in a row ?

in your screenshot i can see "beliebt" and "neuerscheinungen" that are functions ? or demo input

**Comment by julialoeschel** [comment]
Hey there, 
I think this is not a appropriate first userstory - it looks more like the 3rd or 4th.  In that case, Chis-yoos idears are valid 🐜 . 

try to start from scratch.
In the fist story you need some data and display the data in a certain manner. This shall be the first thing to do. 
After that you could implement, that you have two  sections that displays your data filtered (beliebt/neu) and 3rd may be the onClick display card (this content here). 

I hope you get where this is going. 
:octocat:  :octocat:  :octocat:

**Comment by PReichetanz** [comment]
Hi Chris,

I really like the change to add mock data already at this point!

Just one thing about the acceptance criteria:
They are used so that the **client** can check them (and he/she is not a developer).
- This is why the flexbox and JSON criteriae should rather be tasks.
- The global style of the app (375x667px) is not correct: Your app needs to look good on every device (this will also be checked during the Quality Assurance). It's fine to create the Figma design on this size or to use the mobile view of your browser with this size during development, but you need to test the other ratios as well.

You could write something like this:
- On each card, the information for likes, views, rating, and bookmark are visible.
- The main content below the header scroll vertically if there is too much content for the display.
