### ISSUE TITLE
Style Search bar, adding mockup JSON with data

### ISSUE THREAD

**Issue by devchristiansimon** [devchristiansimon/capstone-user-stories#6]
## Value Proposition

**As  user
**I need search bar with 2 buttons
**to be able to see the search bar

## Description

![chrome_Cj5lfQ2Zyn](https://user-images.githubusercontent.com/14675664/179755447-e58dde9c-523b-4fba-91c4-721c58c21560.png)

## Acceptance Criteria

- [ ] adding search bar style
- [ ] video / article button for filtering

## Tasks

(for developers team)

- [ ] design a bar between header and content
- [ ] integrate an input field with an magnifying glass right to it
- [ ] integrate 2 buttons (Video, Article) right to the search button
- [ ] creating a JSON file with default array values

**Comment by PReichetanz** [comment]
Hi Christian,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Value Proposition
- Please make sure the markdown is formatted correctly: The two asterisks ** should not be visible, instead, "As a" (i.e. the start of each line) should be bold.

## Description
- I don't think that you need a navigation at the bottom, do you?
- I was wondering about this several times: What is the mysterious orange form and the 150 at the upper right corner used for? Is it something the user can already work with?

## Acceptance Criteria
- The first criteria is not a good one, because the client can check the style via the wireframe. What would be better is something like this:
  - On initial render, all available content cards are shown.
  - The user is required to put at least one character into the search bar to submit the search.
  - If there is no content card found, ... [What happens then? Fill in the gap yourself ;) ]

## Tasks
- Add an accessible label for the search bar (search for "sr-only" styling)

**Comment by chris-yooo** [comment]
after changes from paul i thinks thats a perfect user story 2 :)

<3
